### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 3000
}

### cancel transaction
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7bfee7db59404bf5952954d45ac4bf4b",
  "accountNumber": "1000000000",
  "amount": 3000
}

### query transaction
GET http://localhost:8080/transaction/44589d90fc244bb5b151601be545c870